### ISSUE TITLE
Run inference in simulation?

### ISSUE THREAD

**Issue by andpuc23** [enyen/KOVIS_VisualServo#1]
Hi!
Thank you for the great work, your code is consice and easy-understandable. However, I didn't find an option to run the model in inference mode using PyBullet simulation and not the real robot. Is there such possibilty? 
I'm not sure I want to risk my UR and the setup in the laboratory.

Thanks in advance!

**Comment by enyen** [comment]
Hi, you are right. Pybullet is only used here for generating training data, no inference simulation is implemented. It is possible though to implement it with the existing functions (e.g. get_image, apply_tcp_speed) with the trained model. New PR is always welcomed.
